services:
  app:
    build: .
    restart: always
    environment:
      - ENV=production
      - TZ=Asia/Jakarta
    ports:
      - "3004:8000"
    volumes:
      - ./docker/app/log:/app/log
      - ./config:/app/config
